---
# tasks file for jefg60.chococygwin

- name: install cyg-get
  win_chocolatey:
    name: cyg-get
    state: present

- name: install additional cygwin binaries
  block:
  - name: stat cygwin binaries
    win_stat:
      path: "c:\\tools\\cygwin\\bin\\{{ item }}.exe"
    register: cyg_get_bin_stats
    with_items: "{{ cyg_get_packages }}"

  - name: check if cygwin binaries are missing
    set_fact:
      missing_cygwin_pkgs: true
    when: item.stat.exists  == false
    with_items: "{{ cyg_get_bin_stats.results }}"

  - name: cyg-get packages
    win_command: "cyg-get.bat {{ cyg_get_packages|join(' ') }}"
    when: missing_cygwin_pkgs is defined and missing_cygwin_pkgs == true
  #skip this block if cyg_get_packages undefined
  when: cyg_get_packages is defined

- name: upgrade existing cygwin pkgs
  win_command: "cyg-get.bat -upgrade all"
  when: cyg_upgrade
  changed_when: false
